name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Ícones no estilo iOS
  cupertino_icons: ^1.0.8

  # Requisições HTTP
  http: ^0.13.6 

  # Gerenciamento de estado
  provider: ^6.1.0

  # Armazenamento local
  shared_preferences: ^2.2.2

  # Animações e transições
  flutter_animate: ^4.5.0

  # Manipulação de datas
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Definindo fontes personalizadas
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

  # Adicionar imagens na pasta assets e descomente para usá-las
  # assets:
  #   - assets/images/
