version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-persona
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persona
    ports:
      - "3306:3306"
    volumes:
      - mysql-persona-data:/var/lib/mysql
    restart: always

volumes:
  mysql-persona-data:
  

  # docker-compose up -d